Algortitmo "Padocs da Fatec"
Var opcao: inteiro
Inicio
escreval("Padocs da Fatec")
escreval("Escolha uma Opção:")
escraval("1- Baguete 2- Café 3- Coca 1L 4- Croissant!")
leia(opcao)

escolha(opcao)
    caso 1
        escreval("Valor R$ 6.00")
    caso 2
        escreval("Valor R$ 7.00")
    caso 3
        escreval("Valor R$ 5.00")
    caso 4
        escreval("Valor R$ 4.00")
    outrocaso
        escreval("Não temos essa opção.")

Fimalgoritmo